version: '3.8'

services:
  backend:
    build: ./BackEnd
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=${MONGO_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - PORT=${PORT}
      - HOST=${HOST}
    depends_on:
      - mongo

  frontend:
    build: ./Front-end
    ports:
      - "5173:80"
    depends_on:
      - backend

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: